"""Add plan trial expires scheduled send and personalization fields

Revision ID: 40bb2f64dd1d
Revises: 
Create Date: 2026-06-04 09:17:56.947503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bb2f64dd1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('scheduled_send_at', sa.DateTime(), nullable=True))
    op.add_column('recipients', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('recipients', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('recipients', sa.Column('role', sa.String(), nullable=True))
    op.add_column('recipients', sa.Column('extra_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(), server_default='trial', nullable=False))
    op.add_column('users', sa.Column('trial_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_expires_at')
    op.drop_column('users', 'plan')
    op.drop_column('recipients', 'extra_data')
    op.drop_column('recipients', 'role')
    op.drop_column('recipients', 'last_name')
    op.drop_column('recipients', 'first_name')
    op.drop_column('campaigns', 'scheduled_send_at')
    # ### end Alembic commands ###
